version: "3.7"
services:
  mysql_db:
    image: "mysql:8.0"
    container_name: MYSQL_DB
    restart: always
    env_file: ./.env
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USERNAME}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    networks:
      - myths
    volumes:
      - data_volume:/data/mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api_service:
    container_name: MYTHS_REST_API
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
    networks:
      - myths
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - service_volume:/data/myths_rest_api

networks:
  myths:

volumes:
  data_volume:
  service_volume: